name: üìù RootCA Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

permissions:
  pull-requests: write
  contents: write
  issues: write
  repository-projects: write

jobs:
  rootca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: projectdiscovery/actions/setup/git@v1
      - uses: projectdiscovery/actions/setup/go@v1
      - run: go install github.com/projectdiscovery/tlsx/cmd/update-rootcerts@latest
      - run: update-rootcerts -out-root-certs ./assets/root-certs.pem
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: root CA update'
          title: 'chore: root CA update'
          body: 'Automated root CA certificates update'
          branch: chore/root-ca-update
          delete-branch: true
